### ISSUE TITLE
quickstart error

### ISSUE THREAD

**Issue by lingHAYAO** [jonasricker/aeroblade#6]
I use run_aeroblade.py to test my own image but it doesn't work.
```
Directory 'aeroblade_output' exists, continue? (y/n) y
PROGRESS (compute_distances):   0%|                                                                                                                                                     | 0/3 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/chenzhehan/aeroblade/scripts/run_aeroblade.py", line 87, in <module>
    main(parse_args())
  File "/home/chenzhehan/aeroblade/scripts/run_aeroblade.py", line 15, in main
    distances = compute_distances(
  File "/home/chenzhehan/aeroblade/scripts/aeroblade/high_level_funcs.py", line 73, in compute_distances
    dist_dict, files = distance_from_config(
  File "/home/chenzhehan/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/chenzhehan/aeroblade/scripts/aeroblade/distances.py", line 35, in compute
    raise ValueError("ds_a and ds_b should contain matching files.")
ValueError: ds_a and ds_b should contain matching files.
PROGRESS (compute_distances):   0%|                                                                                                                                                     | 0/3 [00:00<?, ?it/s]
```

**Comment by jonasricker** [comment]
This is probably an issue with caching. Try deleting the output directory and the `.cache` directory.

**Comment by ayushgoyal9715** [comment]
Even after deleting the output directory and .cache it's still showing the same error
![image](https://github.com/user-attachments/assets/00b6d1dd-54a4-4e6c-9a11-3c0004bff063)

**Comment by jonasricker** [comment]
Could you debug with a breakpoint at the following [line](https://github.com/jonasricker/aeroblade/blob/901b898144430e0c842f15f730415fcd177d77c2/src/aeroblade/distances.py#L35) and print `files_a` and `files_b`?

**Comment by ayushgoyal9715** [comment]
![image](https://github.com/user-attachments/assets/fb30f2ba-ce5a-46d6-a6fe-324d9a974b98)
Because of the format, it will only work on png images
