### ISSUE TITLE
quickstart error

### ISSUE THREAD

**Issue by 1171000712** [jonasricker/aeroblade#9]
Hello, I tried to use "python scripts/run_aeroblade.py   --files-or-dirs   ./example_images" to test example imgs you gave but got following error.
Reconstructing with CompVis/stable-diffusion-v1-1.: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:05<00:00,  1.53it/s]
Images saved to aeroblade_output/reconstructions/6035d99991c3f2b0d82c1972bb1f8309/1.███████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:05<00:00,  2.42it/s]
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [on]
Loading model from: /root/miniconda3/envs/blade/lib/python3.10/site-packages/lpips/weights/v0.1/vgg.pth
Computing LPIPS: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:01<00:00,  7.98it/s]
Traceback (most recent call last):█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:01<00:00, 10.81it/s]
  File "/autodl-fs/data/aeroblade/scripts/run_aeroblade.py", line 87, in <module>
    main(parse_args())
  File "/autodl-fs/data/aeroblade/scripts/run_aeroblade.py", line 15, in main
    distances = compute_distances(
  File "/autodl-fs/data/aeroblade/src/aeroblade/high_level_funcs.py", line 73, in compute_distances
    dist_dict, files = distance_from_config(
  File "/root/miniconda3/envs/blade/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/autodl-fs/data/aeroblade/src/aeroblade/distances.py", line 44, in compute
    result = self._compute(
  File "/autodl-fs/data/aeroblade/src/aeroblade/distances.py", line 194, in _compute
    return _compute_lpips(
  File "/root/miniconda3/envs/blade/lib/python3.10/site-packages/joblib/memory.py", line 655, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/root/miniconda3/envs/blade/lib/python3.10/site-packages/joblib/memory.py", line 598, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/root/miniconda3/envs/blade/lib/python3.10/site-packages/joblib/memory.py", line 856, in call
    output = self.func(*args, **kwargs)
  File "/autodl-fs/data/aeroblade/src/aeroblade/distances.py", line 161, in _compute_lpips
    lpips_layers = [torch.cat(lpips_layer) for lpips_layer in lpips_layers]
  File "/autodl-fs/data/aeroblade/src/aeroblade/distances.py", line 161, in <listcomp>
    lpips_layers = [torch.cat(lpips_layer) for lpips_layer in lpips_layers]
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 512 but got size 1024 for tensor number 1 in the list.
PROGRESS (compute_distances):   0%|                                                                                                                                                                    | 0/3 [00:13<?, ?it/s]

**Comment by jonasricker** [comment]
If you provide a directory, all images in the directory must have the same dimension, since we do not perform resizing or cropping. However, it works if you pass a list of paths to single files, which is also what happens if you run `run_aeroblade.py` with default arguments. I also added a note in the README.
